kind: Service
apiVersion: v1
metadata:
  name: spark-operator-webhook
  namespace: spark-operator
  labels:
    app.kubernetes.io/name: sparkoperator
spec:
  ports:
  - port: 443
    targetPort: 8080
    name: webhook
  selector:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v1beta2-1.2.0-3.0.0
